var autoObject = new tw.object.toolkit.COTK.OnboardingInformation();
autoObject.client = new tw.object.toolkit.COTK.Client();
autoObject.client.name = "Automation Elite Inc.";
autoObject.client.primaryContact = new tw.object.toolkit.COTK.PrimaryContact();
autoObject.client.primaryContact.firstName = "June Marie";
autoObject.client.primaryContact.lastName ="Sample";
autoObject.client.primaryContact.email ="jmarie@example.com";
autoObject.client.primaryContact.phoneNumber ="517-555-0000";
autoObject.client.address = new tw.object.toolkit.COTK.Address();
autoObject.client.address.street = "3974 Carson St"; autoObject.client.address.unit = "1A";
autoObject.client.address.city ="Lansing";
autoObject.client.address.zipCode = "48911";
autoObject.client.address.state = "MI";
autoObject.client.address.country = "United States of America";
autoObject.client.additionalInformation = new tw.object.toolkit.COTK.ClientInformation();
autoObject.client.additionalInformation.annualRevenue = 50000000;
autoObject.client.additionalInformation.companyAge = 10;
autoObject.client.additionalInformation.defaultedPayment = true;
autoObject.client.additionalInformation.numberOfEmployees = 1200;
autoObject.segment = "Segment 1";
autoObject.servicesInfo = new tw.object.toolkit.COTK.ServicesInformation();
autoObject.servicesInfo.servicesFee = 2500;
autoObject.servicesInfo.industry = "Telecom";
autoObject.servicesInfo.servicesRequested = "Fibre Internet";
autoObject.approvalStatus = "Approved";
autoObject
